### ISSUE TITLE
Inloggen Ziggo Go werkt niet.

### ISSUE THREAD

**Issue by THX1180** [dut-iptv/dut-iptv#141]
Allereerst dank voor deze toffe addon! (Ziggo Go)

Heb alles volgens het boekje gedaan en geïnstalleerd op mijn smart-tv (Android TV+kodi 19.3), het lukt mij echter niet om in te loggen en het werkend te krijgen. Ik krijg de Check Username melding en daarmee houdt het in principe op...

Helaas dus niet kunnen testen.

Is hier een fix voor?

Alvorens bedankt!👍

**Comment by 3DSBricker** [comment]
Hoi, de eigenaar reageert al een tijdje niet meer en toen ik deze add-on had gevonden, vond ik het erg zonde om het gewoon zo (dood/niet werkend) te laten. Ik vroeg me af waarom het niet werkte en ben er in geslaagd alles werkend te krijgen. Zie #135
Nou moet ik er wel gelijk bij zeggen, dat de EPG uit het niets is gestopt. Daar haalt de plugin zijn IDs voor replay en het zoeken/searching ook vandaan, dit werkt dus niet meer (dit is sinds ongeveer een week zo). Voor nu blijft het bij live TV, maar ik ben bezig cloud opnames te laten werken. Misschien verdiep ik me nog eens in de EPG, aangezien ik daar geen source code van heb. Op het moment heb ik niet veel tijd, maar als het werkt, of iemand is me voor, dan kun je het weer gebruiken. Tot die tijd hoop ik dat de eigenaar wat heeft aan mijn oplossingen en dat kan gebruiken voor een definitieve fix. Dit alles komt door een nieuw systeem van Ziggo. 
Een oplossing is dus om uit mijn issue (#135) het ZIP bestand te downloaden en te installeren.

**Comment by THX1180** [comment]
Super bedankt... 

Ik ga het later allemaal is eventjes proberen.

Dus eigenlijk moet ik de oude versie installeren en dan de bestanden vervangen met de nieuwe? 

Laat het je weten!🔥

**Comment by 3DSBricker** [comment]
In precipe kun je gewoon de ZIP installeren. Je kunt ook handmatig de bestanden vervangen, maar op een TV is dat wat minder handig lijkt me.

**Comment by kaoloboy** [comment]
Als ik m installeer vanuit de zip file krijg ik helaas nog steeds dezelfde login fail melding. Bedankt in ieder geval voor al je werk.

**Comment by 3DSBricker** [comment]
Heb je de vorige verwijderd, of de add-on al geprobeerd te resetten? Ik hoefde dat niet, maar sommigen hebben gezegd dat zij het wel moesten voor ze konden inloggen.

**Comment by kaoloboy** [comment]
Ik heb beide opties geprobeerd, zonder succes.

**Comment by kersvanbinsbergen** [comment]
Goed om te zien dat er aan gewerkt wordt.

Bedankt daarvoor.

Reclame doorspoelen op de commerciële was een zegen.

**Comment by srozemuller** [comment]
Het klinkt misschien een beetje gek, maar hoe log ik in op deze addon? De addon crashed gelijk op moment van starten in Kodi. 
Ik gebruik Kodi 19.5 matrix op een RPI 4. Zowel de fix uit #135 geinstalleerd maar geen oplossing.
Een deel van de loggin rondom het ziggo start proces staat hieronder..

Lijkt iets met Python maar weet zo niet wat. 

`2023-01-29 12:36:22.350 T:641     ERROR <general>: Control 55 in window 10025 has been asked to focus, but it can't
2023-01-29 12:36:22.437 T:895      INFO <general>: initializing python engine.
2023-01-29 12:36:23.468 T:878      INFO <general>: Python interpreter stopped
2023-01-29 12:36:27.192 T:895      INFO <general>: Skipped 3 duplicate messages..
2023-01-29 12:36:27.192 T:895     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: 'NoneType' object is not subscriptable
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.ziggo/default.py", line 1, in <module>
                                                       from resources.lib.base.l8.menu import plugin
                                                     File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/l8/menu.py", line 5, in <module>
                                                       from resources.lib.api import api_add_to_watchlist, api_get_profiles, api_set_profile, api_list_watchlist, api_login, api_play_url, api_remove_from_watchlist, api_search, api_vod_download, api_vod_season, api_vod_seasons, api_watchlist_listing
                                                     File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/api.py", line 10, in <module>
                                                       from resources.lib.base.l4.session import Session
                                                     File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/l4/session.py", line 6, in <module>
                                                       from resources.lib.constants import CONST_BASE_DOMAIN, CONST_BASE_DOMAIN_MOD, CONST_BASE_HEADERS, CONST_BASE_IP
                                                     File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/constants.py", line 6, in <module>
                                                       CONST_BASE_IP = dns_lookup('obo-prod.oesp.ziggogo.tv', "1.0.0.1")['A'][0]
                                                   TypeError: 'NoneType' object is not subscriptable
                                                   -->End of Python script error report<--
                                                   
2023-01-29 12:36:28.096 T:895      INFO <general>: Python interpreter stopped
2023-01-29 12:36:28.101 T:894     ERROR <general>: GetDirectory - Error getting plugin://plugin.video.ziggo/
2023-01-29 12:36:28.111 T:641     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ziggo/) failed
2023-01-29 12:39:45.452 T:641      INFO <general>: Loading skin file: DialogContextMenu.xml, load type: KEEP_IN_MEMORY
2023-01-29 12:39:47.419 T:706      INFO <general>: CActiveAESink::OpenSink - initialize sink
2023-01-29 12:39:47.420 T:706      INFO <general>: CAESinkALSA::Initialize - Attempting to open device "hdmi:CARD=vc4hdmi0,DEV=0"
`

**Comment by 3DSBricker** [comment]
Your traceback mentions obo-prod.oesp.ziggogo.tv, this has been replaced by a new url in my fix. Are you sure you're using it correctly? Maybe try uninstalling the plugin and then reinstalling with mine?

**Comment by srozemuller** [comment]
> Your traceback mentions obo-prod.oesp.ziggogo.tv, this has been replaced by a new URL in my fix. Are you sure you're using it correctly? Maybe try uninstalling the plugin and then reinstalling it with mine?

I did reinstall the add-on. although I think I did. I removed the addon from Kodi, restarted the RPI4 then reinstall the addon based on the provided link in: https://github.com/dut-iptv/dut-iptv/issues/135#issuecomment-1248446230

thereafter I restarted Kodi again.

**Comment by srozemuller** [comment]
I also tried to install the addon in a regular way. Then, I overwrite the files with the file out or your repository @3DSBricker  .. Still doesn't work, unfortunately.

**Comment by 3DSBricker** [comment]
Maar is de log van mijn versie of de originele versie? Het is vrijwel onmogelijk om obo-prod.oesp.ziggogo.tv in de constants te hebben. Dat zou betekenen dat de log van de originele versie is, die niet meer werkt. Als het van de originele versie is zou ik graag de log van mijn versie willen zien, aangezien het waarschijnlijk een andere fout is dan die in de log staat. Zelf gebruik ik Kodi Matrix 19.4, maar ik zal binnenkort 19.5 en 20 (Nexus) testen.

**Comment by yaelruhl** [comment]
Er komt nu continu een foutmelding stream niet gevonden bij het openen van een zender

Bij kodi 20
