### ISSUE TITLE
[Ziggo GO] fix: Live TV & recordings

### ISSUE THREAD

**Issue by 3DSBricker** [dut-iptv/dut-iptv#158]
This fixes the Ziggo GO add-on. I still consider this an Alpha release as the code is somewhat messy, which might give problems like streaming session limits (as if you were streaming using many devices at once with Ziggo GO). It does, however, work. It does not crash and you can click away the messages, in case they do show up. This is mainly a problem with Live TV, though. I also added a feature to watch recordings. I might add an option to remove them, but to plan them, I'd need to have a working EPG again, one that includes the necessary IDs, which I haven't found yet. This means replay does not work either. The code itself should theoretically, but there is just nothing you can select. You need to install this manually, and I'm not sure if you need to remove the old one, but I do recommend it. The same applies to the Dut-IPTV proxy. Should work with both Kodi 19 Matrix, and Kodi 20 Nexus. But will be focussed on just Nexus in the future.

The pull request: #136 
The original issue: #135 
My repository: https://github.com/3DSBricker/dut-iptv/tree/master/plugin.video.ziggo
I also added back the installation through the Kodi repository:
[Kodi repo](https://github.com/QuasarKodearring/QuasarKodearring.github.io)

[service.dutiptv.proxy.zip](https://github.com/QuasarKodearring/QuasarKodearring.github.io/raw/master/nexus/service.dutiptv.proxy/service.dutiptv.proxy-latest.zip)
[plugin.video.ziggo.zip](https://github.com/QuasarKodearring/QuasarKodearring.github.io/raw/master/nexus/plugin.video.ziggo/plugin.video.ziggo-latest.zip)

**Comment by tgiesela** [comment]
I did not notice until now that you created a working version for Ziggo GO, so I started a completely new development just for Ziggo GO. I does not have lots of nice features, but it has an EPG which allows you to replay or switch to a channel. It also allows to play movies and series. See: [ziggotv.repo](https://ziggotv.github.io/)

**Comment by 3DSBricker** [comment]
@tgiesela Hi, I tried your add-on and it looks great. It was a bit unstable for me, but so is mine and it's great that it works (been busy lately, mine probably is quite broken). What's up with the 1080P, though? As far as I know that only works with the Android TV app, which requires a Ziggo internet connection.

**Comment by 3DSBricker** [comment]
After one successful playback, I can't get anything to work anymore. Just a message: _`b"`_
According to the log, Ziggo sent 500 bad request apparently which results in KeyError: 'isPremiereAirings'. I need to kill Kodi, because the code doesn't stop by itself. Removing all data did not help.

**Comment by tgiesela** [comment]
Hi,

 

I will check what the issue is. Can you tell me which channel/movie/function did you access? 

I know that for some attributes in the JSON-responses I assume they are always there, but I also noticed that some of them absent in special cases. So when I find one myself, I fix it. So if you can help me to improve it... I will have a look anyway at the field isPremiereAirings.

**Comment by tgiesela** [comment]
I will fix the issue with the KeyError, but I don't this is the reason for the 500 bad request. If the problem is still reproducible, can you create a debug log with the 'Trace network traffic' option on and share the part which causes the 500 bad request?

**Comment by 3DSBricker** [comment]
Hi, recordings are completely unable to load, due to André Kuipers. (last time I checked, it complained about isPremiereAirings and occasionally due to 500 Internal Server Error. Now it's all OK (200) but can't find the shortSynopsis field. Which is the summary. What I previously did was a try and except, sometimes based on the type of program (single, show, series, episode, etc). The serie itself has a shortSynopsis. The episodes have a synopsis. Perhaps a check if synopsis is present, otherwise use shortSynopsis, or none at all. No synopsis is better than no recordings at all. I will take a look at your code later, but I had these issues with my version as well.

```
2024-03-28 09:29:24.083 T:2040    debug <general>: Cookies: 
2024-03-28 09:29:24.083 T:2040    debug <general>:  
2024-03-28 09:29:24.083 T:2040    debug <general>: {'ACCESSTOKEN': 'eyJ0e...4I', 'CLAIMSTOKEN': 'eyJ0e...ao'}
2024-03-28 09:29:24.083 T:2040    debug <general>: 

2024-03-28 09:29:24.083 T:2040    debug <general>: Request data is empty
2024-03-28 09:29:24.083 T:2040    debug <general>: 

2024-03-28 09:29:24.083 T:2040    debug <general>: Response JSON-format: {"images": [{"url": "https://staticqbr-nl-prod.prod.cdn.dmdsdp.com/image-service/ImagesEPG/EventImages/p23909556_b_v12_ab.jpg", "type": "showPoster"}, {"url": "https://staticqbr-nl-prod.prod.cdn.dmdsdp.com/image-service/ImagesEPG/EventImages/p23909556_bd_h10_ab.jpg", "type": "eosShowPoster"}], "seasons": [{"number": 1, "poster": {"url": "https://staticqbr-nl-prod.prod.cdn.dmdsdp.com/image-service/ImagesEPG/EventImages/p23909563_b_v12_ab.jpg", "type": "seasonPoster"}}], "genres": ["Documentaire", "Wetenschap"], "shortSynopsis": "Astronaut Andr\u00e9 Kuipers geeft een unieke blik op Nederland. Hij doet dit aan de hand van indrukwekkende natuurbeelden, nooit eerder vertoonde beelden uit ruimtestation ISS en bijzondere verhalen van bevlogen experts en natuurliefhebbers.", "total": 2, "data": [{"mostRelevant": false, "episodeId": "crid:~~2F~~2Fgn.tv~~2F24166130~~2FEP046271350005,imi:a7f6223da763906812adb91cf23c2bba7f0559d1", "containsAdult": false, "episodeTitle": "Natuurlijk Nederland", "synopsis": "We zien hoe mensen onderdeel zijn van de immense natuur. Hoe we die natuur indammen, en ook weer de ruimte geven.", "background": {"url": "https://staticqbr-nl-prod.prod.cdn.dmdsdp.com/image-service/ImagesEPG/EventImages/p23909563_b_v12_ab.jpg", "type": "HighResPortrait"}, "poster": {"url": "https://staticqbr-nl-prod.prod.cdn.dmdsdp.com/image-service/ImagesEPG/EventImages/p23909563_b_v12_ab.jpg", "type": "episodePoster"}, "showTitle": "Ruimteschip aarde", "expirationDate": "2024-03-28T19:25:00.000Z", "startTime": "2023-03-29T18:34:00.000Z", "prePaddingOffset": 300, "postPaddingOffset": 900, "trickPlayControl": "", "recordingState": "recorded", "recordingType": "nDVR", "technicalDuration": 2737, "seasonNumber": 1, "episodeNumber": 5, "seasonId": "crid:~~2F~~2Fgn.tv~~2F23909563~~2FSH046271350000", "bookmark": 0, "viewState": "notWatched", "endTime": "2023-03-29T19:28:00.000Z", "duration": 2737, "source": "show", "isOttBlackout": false, "isPremiere": true, "isAdult": false}, {"mostRelevant": true, "episodeId": "crid:~~2F~~2Fgn.tv~~2F24200236~~2FEP046271350006,imi:5abace56ea7ab1e42bc9cc56d5fc213d9aac6a7c", "containsAdult": false, "episodeTitle": "17 Miljoen mensen", "synopsis": "We zoomen in op 'de mens', misschien wel de vreemdste diersoort op Ruimteschip Aarde, die overal z'n sporen achterlaat.", "background": {"url": "https://staticqbr-nl-prod.prod.cdn.dmdsdp.com/image-service/ImagesEPG/EventImages/p23909563_b_v12_ab.jpg", "type": "HighResPortrait"}, "poster": {"url": "https://staticqbr-nl-prod.prod.cdn.dmdsdp.com/image-service/ImagesEPG/EventImages/p23909563_b_v12_ab.jpg", "type": "episodePoster"}, "showTitle": "Ruimteschip aarde", "expirationDate": "2024-04-04T19:27:00.000Z", "startTime": "2023-04-05T18:33:00.000Z", "prePaddingOffset": 300, "postPaddingOffset": 900, "trickPlayControl": "", "recordingState": "recorded", "recordingType": "nDVR", "technicalDuration": 3240, "seasonNumber": 1, "episodeNumber": 6, "seasonId": "crid:~~2F~~2Fgn.tv~~2F23909563~~2FSH046271350000", "bookmark": 0, "viewState": "notWatched", "endTime": "2023-04-05T19:27:00.000Z", "duration": 3240, "source": "show", "isOttBlackout": false, "isPremiere": true, "isAdult": false}], "size": 2}
2024-03-28 09:29:24.083 T:2040    debug <general>: 
                                                   
2024-03-28 09:29:24.094 T:2040    debug <general>: HTTP GET Request processed: /function/refresh_recordings?args={"includeAdult":+false}
2024-03-28 09:29:24.099 T:2040    debug <general>: HTTP GET Request received: /function/get_recordings?args={}
2024-03-28 09:29:24.131 T:2040    error <general>: Exception in handle_get(): 'shortSynopsis'
2024-03-28 09:29:24.132 T:2040    debug <general>: Traceback (most recent call last):
                                                     File "C:\Users\<redacted>\AppData\Roaming\Kodi\addons\plugin.video.ziggotv\resources\lib\proxyserver.py", line 206, in handle_get
                                                       self.handle_function(request)
                                                     File "C:\Users\<redacted>\AppData\Roaming\Kodi\addons\plugin.video.ziggotv\resources\lib\proxyserver.py", line 354, in handle_function
                                                       retval = callableMethod(**args)
                                                     File "C:\Users\<redacted>\AppData\Roaming\Kodi\addons\plugin.video.ziggotv\resources\lib\webcalls.py", line 1152, in get_recordings
                                                       return RecordingList(recordingsInfo['recorded'])
                                                     File "C:\Users\<redacted>\AppData\Roaming\Kodi\addons\plugin.video.ziggotv\resources\lib\recording.py", line 263, in __init__
                                                       season = SeasonRecording(data)
                                                     File "C:\Users\<redacted>\AppData\Roaming\Kodi\addons\plugin.video.ziggotv\resources\lib\recording.py", line 169, in __init__
                                                       self.synopsis = episodes['shortSynopsis']
                                                   KeyError: 'shortSynopsis'

```

Also figured out how you managed 1080P channels, live channels at 1080P only work on Ziggo IP (correct me if I'm wrong):
```

2024-03-28 09:31:35.783 T:23228   debug <general>: HTTP GET Request received: /function/obtain_tv_streaming_token?args={"channelId":+"NL_000001_019401",+"assetType":+"Orion-DASH-HEVC"}
2024-03-28 09:31:35.824 T:22744   debug <general>: ZIGGOPLAYER CREATED
2024-03-28 09:31:35.864 T:23228   debug <general>: URL: POST https://prod.spark.ziggogo.tv/eng/web/session-service/session/v2/web-desktop/customers/514601_nl/live?channelId=NL_000001_019401&assetType=Orion-DASH-HEVC&profileId=<REDACTED>&liveContentTimestamp=2024-03-28T08%3A31%3A35.782861%2B00%3A00
2024-03-28 09:31:35.864 T:23228   debug <general>: 
                                                   
2024-03-28 09:31:35.864 T:23228   debug <general>: Status-code: 403
2024-03-28 09:31:35.864 T:23228   debug <general>: 
                                                   
2024-03-28 09:31:35.864 T:23228   debug <general>: Request headers: {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.9,nl;q=0.8', 'Cache-Control': 'no-cache', 'DNT': '1', 'TE': 'trailers', 'Origin': 'https://www.ziggogo.tv', 'Pragma': 'no-cache', 'Referer': 'https://www.ziggogo.tv/', 'Sec-Fetch-Dest': 'empty', 'Sec-Fetch-Mode': 'cors', 'Sec-Fetch-Site': 'same-site', 'X-Device-Code': 'web', 'X-OESP-Username': '<REDACTED>', 'x-tracking-id': 'af...0c', 'X-Profile': '<REDACTED>', 'Cookie': 'ACCESSTOKEN=eyJ0e...Pk; CLAIMSTOKEN=eyJ0e...oE', 'Content-Length': '0'}
2024-03-28 09:31:35.864 T:23228   debug <general>: 
                                                   
2024-03-28 09:31:35.864 T:23228   debug <general>: Response headers: {'Content-Type': 'application/json', 'Content-Length': '211', 'Timing-Allow-Origin': '*', 'Server-Timing': 'dtRpid;desc="1858732402", dtTao;desc="1", dtSInfo;desc="0"', 'X-OneAgent-JS-Injection': 'true', 'x-request-id': '1bcbad899e8c6a383c31c650656abf7d', 'X-Content-Type-Options': 'nosniff', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Methods': 'GET, POST, PUT, OPTIONS, DELETE, HEAD, PATCH', 'Access-Control-Allow-Headers': 'Accept-Charset, Accept-Encoding, Access-Control-Request-Headers, Access-Control-Request-Method, Authorization, Cache-Control, Connection, Content-Encoding, Content-Type, Content-Length, Cookie, DNT, Date, Host, If-Modified-Since, Keep-Alive, Origin, Referer, Server, TokenIssueTime, Transfer-Encoding, User-Agent, Vary, X-CustomHeader, X-Requested-With, password, username, x-request-id, x-ratelimit-app, x-guest-token, X-HTTP-Method-Override, x-oesp-username, x-oesp-token, x-cus, x-dev, X-Client-Id, X-Device-Code, X-Language-Code, UserRole, x-session-id, x-entitlements-token, x-go-dev, x-profile, x-api-key, nv-authorizations, X-Viewer-Id, x-oesp-profile-id, x-streaming-token, x-streaming-token-refresh-interval, x-drm-device-id, x-profile-id, x-ui-language, deviceName, x-drm-schemeId, x-refresh-token, X-Username, Location, x-tracking-id, x-lgi-target, x-cvp', 'Access-Control-Expose-Headers': 'x-streaming-token, x-streaming-token-refresh-interval, x-drm-device-id, x-profile-id, x-ui-language, deviceName, x-drm-schemeId, nv-qm-signature, nv-qm-version, x-refresh-token, Location, x-lgi-target, x-cvp', 'Access-Control-Max-Age': '1728000', 'X-EdgeConnect-MidMile-RTT': '7', 'X-EdgeConnect-Origin-MEX-Latency': '23', 'Date': 'Thu, 28 Mar 2024 08:30:58 GMT', 'Connection': 'close', 'Set-Cookie': 'dtCookie=v_4_srv_31_sn_55...F0_perc_100000_ol_0_mul_1_app-3Aea7c4b59f27d43eb_1; Path=/; Domain=.horizon.tv', 'Access-Control-Allow-Origin': 'https://www.ziggogo.tv'}
2024-03-28 09:31:35.864 T:23228   debug <general>: 
                                                   
2024-03-28 09:31:35.864 T:23228   debug <general>: Cookies: 
2024-03-28 09:31:35.864 T:23228   debug <general>:  
2024-03-28 09:31:35.864 T:23228   debug <general>: {'ACCESSTOKEN': 'eyJ0e...Pk', 'CLAIMSTOKEN': 'eyJ0e...oE'}
2024-03-28 09:31:35.864 T:23228   debug <general>: 
                                                   
2024-03-28 09:31:35.864 T:23228   debug <general>: Request data is empty
2024-03-28 09:31:35.864 T:23228   debug <general>: 
                                                   
2024-03-28 09:31:35.865 T:23228   debug <general>: Response JSON-format: {"error": {"httpStatusCode": 403, "statusCode": 1111, "message": "In order to watch this, you need to be on your WiFi network.", "details": "lgi-nl-prod-master:onnet", "correlationId": "1b...7d"}}
2024-03-28 09:31:35.865 T:23228   debug <general>: 
```

**Comment by tgiesela** [comment]
I fixed the issue with the parsing of the JSON. I cannot test this, because when I do record myself, I can always play the recordings. So I'm not sure why this happens in your recordings (they are rather old as far as I can see).
And yes 1080p only works in live channels. Play recording and replay works only in a lower resolution. I could not find a way to play them in 1080p. If you know how, please let me know.
