### ISSUE TITLE
[Ziggo][1.0.0] API errors

### ISSUE THREAD

**Issue by BP-onthemove** [dut-iptv/dut-iptv#32]
Unable to use add-on, also after a fresh installation on 3 android devices

**To Reproduce**
After going through the wizard I log in and then I get these errors with live and Replay TV in Kodi 18.9 and Wonderboy 18.9

Log;

2021-03-14 22:19:03.801 T:25077   ERROR: plugin.video.ziggo - 'sharedProfileId'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/tv.wonderbox.www/files/.kodi/addons/plugin.video.ziggo/resources/lib/base/l5/signals.py", line 29, in throwable
                                                yield
                                              File "/storage/emulated/0/Android/data/tv.wonderbox.www/files/.kodi/addons/plugin.video.ziggo/resources/lib/base/l6/router.py", line 94, in dispatch
                                                function(**params)
                                              File "/storage/emulated/0/Android/data/tv.wonderbox.www/files/.kodi/addons/plugin.video.ziggo/resources/lib/base/l7/plugin.py", line 34, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "/storage/emulated/0/Android/data/tv.wonderbox.www/files/.kodi/addons/plugin.video.ziggo/resources/lib/base/l8/menu.py", line 72, in login
                                                login_result = api_login()
                                              File "/storage/emulated/0/Android/data/tv.wonderbox.www/files/.kodi/addons/plugin.video.ziggo/resources/lib/api.py", line 292, in api_login

**Expected behavior**

**Screenshots**
![Screenshot_20210314-221928_WBMC 189](https://user-images.githubusercontent.com/21219067/111085134-4ea2d100-8516-11eb-9b1b-614ccb9f0db2.png)

**Device (please complete the following information):**
Nvidia Shield 2019 and 2017 and Samsung S20+

**Additional context**

**Comment by dut-iptv** [comment]
Leia is unsupported since 1.0.0.

If providers change things that break login/playback I won't be fixing them.

Ziggo has done this recently, which is a shame, but this means you will not be able to use the addon in Leia.

Closing
