### ISSUE TITLE
[Dut-IPTV Simple IPTV Connector][1.2.1+matrix.1] Installation error on OSMC

### ISSUE THREAD

**Issue by Uome** [dut-iptv/dut-iptv#59]
I wanted to install dut-iptv on a fresh install of OSMC (Kodi 19.1) on a Raspberry Pi 4.

To this end, I followed the instructions, including the additional instructions for general Linux / OSMC. 

Downloading the add-on from the repository worked fine. However, when trying to open Dut-IPTV Simple IPTV Connector from the repository, I receive an error.

The log seems to suggest a Cryptodome related error:

> Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'Cryptodome'
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/plugin.executable.dutiptv/service.py", line 1, in <module>
                                                       from resources.lib.service import main
                                                     File "/home/osmc/.kodi/addons/plugin.executable.dutiptv/resources/lib/service.py", line 3, in <module>
                                                       from resources.lib.api import api_get_channels, api_get_all_epg
                                                     File "/home/osmc/.kodi/addons/plugin.executable.dutiptv/resources/lib/api.py", line 6, in <module>
                                                       from resources.lib.base.l3.util import check_key, fixBadZipfile, is_file_older_than_x_days, load_file, load_profile, write_file
                                                     File "/home/osmc/.kodi/addons/plugin.executable.dutiptv/resources/lib/base/l3/util.py", line 5, in <module>
                                                       from resources.lib.base.l1.encrypt import Credentials
                                                     File "/home/osmc/.kodi/addons/plugin.executable.dutiptv/resources/lib/base/l1/encrypt.py", line 2, in <module>
                                                       from Cryptodome import Random
                                                   ModuleNotFoundError: No module named 'Cryptodome'
                                                   -->End of Python script error report<--<--]

**Comment by dut-iptv** [comment]
For Kodi 19/Python 3 the commands are:
```
sudo apt-get install python3-crypto
sudo apt-get install build-essential python3-pip
sudo python3 -m pip install -U setuptools
sudo python3 -m pip install wheel
sudo python3 -m pip install pycryptodomex
```
