### ISSUE TITLE
[Ziggo Go][LibreElec 9.2] KeyError: 'SharedProfileId'

### ISSUE THREAD

**Issue by Thomasolicious** [dut-iptv/dut-iptv#64]
After logging in to Ziggo Go account the following error occurs:
```
2021-09-02 12:55:38.129 T:1470096256   DEBUG: plugin.video.ziggo - SIGNAL: on_exception
2021-09-02 12:55:38.133 T:1470096256   ERROR: plugin.video.ziggo - 'sharedProfileId'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/l5/signals.py", line 29, in throwable
                                                yield
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/l6/router.py", line 94, in dispatch
                                                function(**params)
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/l7/plugin.py", line 34, in decorated_function
                                                item = f(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/base/l8/menu.py", line 72, in login
                                                login_result = api_login()
                                              File "/storage/.kodi/addons/plugin.video.ziggo/resources/lib/api.py", line 292, in api_login
                                                ziggo_profile_id = data['customer']['sharedProfileId']
                                            KeyError: 'sharedProfileId'
2021-09-02 12:55:38.134 T:1470096256   DEBUG: plugin.video.ziggo - SIGNAL: on_close
```

Also, after declining the message none of the content is loaded (~ No Items ~) and Settings > Reset Session results in the same error message.

1. On LibreElec 9.2 install repo from zip
2. Install Ziggo Go from repo
3. Login to Ziggo Go account

**Comment by dut-iptv** [comment]
Kodi 18 is not supported anymore. Upgrade to libreelec 10

**Comment by Thomasolicious** [comment]
Thanks for the clarification. The readme still states that kodi 18+ with widevine support is still supported, hence I gave it a try.
